### ISSUE TITLE
How to easly use NimBLE library

### ISSUE THREAD

**Issue by roboticboyer** [senseshift/arduino-ble-serial#6]
To use NimBLE library to save a significant amount of RAM and Flash memory write as below in the sketch without modifying the library

```
#define BLESERIAL_USE_NIMBLE true // to be added to use NimBLE https://github.com/h2zero/NimBLE-Arduino
#include <BLESerial.h> // https://github.com/senseshift/arduino-ble-serial

```

**Comment by leon0399** [comment]
Thank you, @roboticboyer! I've included your example in the readme!
