### ISSUE TITLE
Quick question: ESP32 D1 Mini

### ISSUE THREAD

**Issue by RandoSY** [senseshift/arduino-ble-serial#7]
Thanks` for this great library.

I'm using a simple, inexpensive ESP32-WROOM32 based D1 Mini, that has a CP2102 UART to USB converter to program the chip, which is working no problem. I loaded the demo code but am not seeing the input from my Android BLE Terminal program, out COM8 which is the serial port assigned to the SiLabs chip. 

![3$ Mini D1 ESP32](https://github.com/user-attachments/assets/7e3f621f-1a9c-4ac6-82fa-fb308caa5e7b)

I wrote a short test program that tests the validity of my COM port connection...  

![Screenshot 2024-08-17 163307](https://github.com/user-attachments/assets/57b4b72f-294e-4463-bce7-9b685db8080e)

![Screenshot 2024-08-17 165200](https://github.com/user-attachments/assets/9fa01dfb-8339-411a-8747-1c2ddcbeec02)

But when I test the serial connection it's  fine transmitting back out to BLE , but I don't see what I transmit with my BLE Terminal Program from my phone. To be clear, communication is only working back out to the BLE terminal program, and I don't see what I type back,  out on the serial port on my ESP32 Mini?

Ideas?

**Comment by RandoSY** [comment]
Got a new phone, installed my best BLE Terminal program, was a little difficult to install, but worked from the Webpage interface of the PlayStore. 

This worked perfectly.

![Screenshot 2024-08-17 173341](https://github.com/user-attachments/assets/8718d126-8e62-4a14-a12e-a3b7eb50384b)

**Comment by RandoSY** [comment]
Thanks again for posting and all your hard work!

**Comment by leon0399** [comment]
I'm glad everything worked out! Thank you for using this library!
